
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RPostgreSQL)
library(tidyverse)
library(sf)
library(git2rdata)
library(inbodb)
```

```{r}
con <- connect_inbo_dbase("S0008_00_Meetnetten")
```

# Bezoeken

```{r}

query_bezoeken <- "SELECT 
  PG.name as soortgroep, 
  P.Name as meetnet,
  PR.name as protocol, 
  L.name as locatie, 
  L1.name as hoofdlocatie,
  V.id as visit_id,
  v.validation_status as validatie, 
  V.start_date as datum, 
  V.start_time, 
  V.end_date,
  V.end_time,
  V.created,
  V.updated,
  T.name as taak, 
  case when V.status = 1 then 'Conform protocol'
       when V.status = -1 then 'Weersomstandigheden ongunstig'
       when V.status = -2 then 'Telmethode niet gevolgd'
       when V.status = -3 then 'Geen veldwerk mogelijk - locatie ontoegankelijk'
       when V.status = -4 then 'Geen veldwerk mogelijk - locatie ongeschikt'
       else Null
  end as bezoek_status, 
  U.first_name, 
  U.last_name,
  V.year_target as jaardoel, 
  V.analysis as voor_analyse,
  V.notes as opmerking
  from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_id = P.id
    inner Join staging_Meetnetten.Locations_location L on L.ID = V.location_ID
    left outer Join staging_Meetnetten.Locations_location L1 on L1.ID = L.parent_ID
    inner join staging_Meetnetten.Protocols_protocol PR on PR.id = V.protocol_ID
    left outer join staging_Meetnetten.projects_task T on T.ID = V.task_id
    inner join staging_Meetnetten.accounts_user U on U.ID = V.user_id
  Where 1=1
"
bezoeken_orig <- tbl(con, sql(query_bezoeken)) %>%
  collect()

bezoeken <- bezoeken_orig %>%
  mutate(jaar = as.numeric(format(datum, "%Y")),
         doy = as.numeric(format(datum, "%j")),
         sublocatie = ifelse(is.na(hoofdlocatie), NA, locatie),
         locatie = ifelse(is.na(hoofdlocatie), locatie, hoofdlocatie),
         hoofdteller = str_c(first_name, " ", last_name),
         start_time = as.character(start_time),
         end_time = as.character(end_time)) %>%
  select(-hoofdlocatie, -first_name, -last_name) %>%
  group_by(meetnet, protocol, locatie, jaar, visit_id) %>%
  mutate(i_bezoek = rank(doy)) %>%
  ungroup() %>%
  select(soortgroep, meetnet, protocol, locatie, sublocatie, jaar, datum, doy, i_bezoek, everything()) %>%
  mutate(opmerking = str_replace_all(opmerking, "[\r\n]" , " "))

write_vc(bezoeken, "bezoeken", root = "../raw", sorting = c("soortgroep", "meetnet", "locatie", "sublocatie", "visit_id"), strict = FALSE)

```

# Tellers en gebruikers

```{r}
query_locatie_users <- "
  select PG.name as soortgroep
, P.Name as meetnet
, l.name as locatie
, pl.is_sample
, pl.is_active
, u.first_name
, u.last_name
, u.email
, u.is_staff
from staging_Meetnetten.projects_projectlocation pl
left outer join staging_Meetnetten.Projects_project P on P.ID = pl.project_ID
left join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
left outer join staging_Meetnetten.locations_location l on l.id = pl.location_id
inner join staging_Meetnetten.accounts_user u on u.id = pl.user_id
"
locatie_users <- dbGetQuery(con, query_locatie_users)

query_users <- "
select pg.name as soortgroep
  , p.name as meetnet
  , u.first_name
  , u.last_name
  , u.email
  , u.address as adres
  , u.city as gemeente
  , u.postalcode as postcode
  , u.reference_obs
  , pu.role
  from staging_Meetnetten.projects_projectuser pu
    inner join staging_Meetnetten.projects_project p on p.id = pu.project_id
    inner join staging_Meetnetten.accounts_user u on u.id = pu.user_id
    inner join staging_Meetnetten.projects_projectgroup pg on pg.id = p.group_id"

meetnetten_users <- dbGetQuery(con, query_users)

query_locatie_users_reserve <- "
select PG.name as soortgroep
, P.Name as meetnet
, l.name as locatie
, pl.is_sample
, pl.is_active
, u.first_name
, u.last_name
, u.email
, u.is_staff
, pb.interested
from staging_Meetnetten.projects_projectlocation pl
left outer join staging_Meetnetten.Projects_project P on P.ID = pl.project_ID
left join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
left outer join staging_Meetnetten.locations_location l on l.id = pl.location_id
left outer join staging_Meetnetten.projects_backupuser pb on pb.projectlocation_id = pl.id
inner join staging_Meetnetten.accounts_user u on u.id = pb.user_id
"
locatie_users_reserve <- dbGetQuery(con, query_locatie_users_reserve)

query_tellers <- "Select PG.name as soortgroep
    , P.Name as meetnet
    , V.task_id
    , T.name as taak
    , V.id as visit_id
    , V.start_date as datum
    , V.year_target as jaardoel
    , L.name as locatie
    , PR.name as protocol
    , u.first_name as first_name_hoofdteller
    , u.last_name as last_name_hoofdteller
    , u2.first_name as first_name_medeteller
    , u2.last_name as last_name_medeteller
from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_id = P.id
    left outer join staging_Meetnetten.projects_task T on T.ID = V.task_id
    Inner Join staging_Meetnetten.Locations_location L on L.ID = V.location_ID
    Inner join staging_Meetnetten.Protocols_protocol PR on PR.id = V.protocol_ID
    INNEr JOIN staging_Meetnetten.accounts_user U on U.ID = V.user_id
    left outer join staging_Meetnetten.fieldwork_visit_co_observers CO on CO.visit_id = V.id
    left outer join staging_Meetnetten.accounts_user U2 on U2.ID = CO.user_id
Order by PG.name
    , P.Name
    , L.name
    , V.start_date"

tellers_orig <- dbGetQuery(con, query_tellers)

tellers <- tellers_orig %>%
  mutate(jaar = as.numeric(format(datum, "%Y")),
         hoofdteller = str_c(first_name_hoofdteller, " ", last_name_hoofdteller),
         medeteller = str_c(first_name_medeteller, " ", last_name_medeteller)) %>%
  select(-last_name_medeteller, -last_name_hoofdteller, -first_name_hoofdteller, -first_name_medeteller) %>%
  gather(hoofdteller, medeteller, key = "type_teller", value = "naam_teller") %>%
  filter(naam_teller != "") %>%
  unique()

query_medetellers <- " SELECT
    v.visit_id as visit_id,
    U.first_name, 
    U.last_name
    FROM staging_Meetnetten.fieldwork_visit_co_observers v
    inner join staging_Meetnetten.accounts_user U on U.ID = V.user_id
    Where 1=1
"

medetellers <- tbl(con, sql(query_medetellers)) %>%
  collect()

write_vc(medetellers, "medetellers", root = "../raw", sorting = c("visit_id", "first_name","last_name"), strict = FALSE)
write_vc(meetnetten_users, "meetnetten_users", root = "../raw", sorting = c("meetnet", "last_name"), strict = FALSE)
write_vc(locatie_users, "locatie_users", root = "../raw", sorting = c("meetnet", "locatie", "last_name"))
write_vc(locatie_users_reserve, "locatie_users_reserve", root = "../raw", sorting = c("meetnet", "locatie", "last_name"))
write_vc(tellers, "tellers", root = "../raw", sorting = c("meetnet", "locatie", "visit_id", "type_teller", "naam_teller"), strict = FALSE)

check <- tellers %>%
  group_by(meetnet, locatie, visit_id, type_teller, naam_teller) %>%
  filter(n() > 1)
```


# Werkpakketten en taken

```{r}
query_werkpakket <- "
  select P.Name as meetnet
    , WP.Name as werkpakket
    , WP.Start_date as wp_start
    , WP.end_date as wp_end
  from staging_Meetnetten.Projects_project P
    left outer join staging_Meetnetten.Projects_workpackage WP on WP.project_ID = P.ID
"
werkpakketten_orig <- dbGetQuery(con, query_werkpakket)

werkpakketten <- werkpakketten_orig %>%
  mutate(doy_min = as.numeric(format(wp_start, "%j")),
         doy_max = as.numeric(format(wp_end, "%j")),
         doy_mid = doy_min + round((doy_max - doy_min)/2, 0),
         jaar = as.numeric((format(wp_start, "%Y"))))

query_werkpakket_locaties <- "
  select P.Name as meetnet
, WP.Name as werkpakket
, l.name as locatie
from staging_Meetnetten.projects_workpackage WP
left outer join staging_Meetnetten.Projects_project P on P.ID = WP.project_ID
left outer join staging_Meetnetten.projects_workpackage_locations wpl on wpl.workpackage_id = wp.id
left outer join staging_Meetnetten.locations_location l on l.id = wpl.location_id
"

werkpakketten_locaties <- dbGetQuery(con, query_werkpakket_locaties)

query_taken <- "
  select PG.Name as soortgroep
    , P.Name as meetnet
    , L.name as locatie
    , WP.Name as werkpakket
    , T.name as taak
    , T.id as task_id
    , PR.name as protocol
    , T.start_date as taak_start
    , T.end_date as taak_end

from staging_Meetnetten.Projects_project P
    INNER JOIN staging_Meetnetten.projects_projectgroup PG on PG.ID = P.group_ID
    left outer join staging_Meetnetten.projects_projectlocation PL on PL.project_id = P.ID
    LEFT OUTER join staging_Meetnetten.Locations_location L ON L.ID = PL.location_ID
    left OUTER join staging_Meetnetten.Projects_workpackage WP on WP.project_ID = P.ID
    LEFT OUTER join staging_Meetnetten.Projects_task T on T.wp_ID = WP.ID and T.location_ID = L.ID
    left Outer JOIN staging_Meetnetten.protocols_protocol PR on PR.id = T.protocol_id

Order by PG.name
    , P.name
    , L.name
    , T.start_date
    , T.name"

taken <- dbGetQuery(con, query_taken)
taken <- taken %>%
  filter(!is.na(taak)) %>%
  mutate(jaar= as.numeric((format(taak_start, "%Y"))))

write_vc(werkpakketten, "werkpakketten", root = "../raw", sorting = c("meetnet", "werkpakket"), strict = FALSE)
write_vc(werkpakketten_locaties, "werkpakketten_locaties", root = "../raw", sorting = c("meetnet", "werkpakket", "locatie"), strict = FALSE)
write_vc(taken, "taken", root = "../raw", sorting = c("soortgroep", "meetnet", "locatie", "werkpakket"), strict = FALSE)
```

# Locaties

```{r}
query_selectLocations <- "SELECT
    PG.name as soortgroep,
    L.name as locatie,
    LT.name as tellocatie_type,
    L.id,
    L.parent_id,
    L.created,
    L.updated,
    P.name as meetnet,
    PL.is_sample,
    PL.is_active,
    PL.user_id,
    PL.projectregion_id,
    L2.name as regio,
    U.first_name,
    U.last_name,
    L.geom.STAsText() as geom_text
    FROM staging_Meetnetten.locations_location L
    INNER JOIN staging_Meetnetten.projects_projectlocation PL ON PL.location_id = L.id
    INNER JOIN staging_Meetnetten.projects_project P ON P.id = PL.project_id
    INNER JOIN staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    LEFT JOIN staging_Meetnetten.accounts_user U on U.ID = PL.user_id
    LEFT JOIN staging_Meetnetten.projects_projectregion R on R.id = PL.projectregion_id
    LEFT JOIN staging_Meetnetten.locations_locationtype LT on LT.id = L.type_id
    LEFT JOIN staging_Meetnetten.locations_location L2 on L2.id = R.location_id
and P.name <> 'Algemene Vlindermonitoring'"

locaties <- dbGetQuery(conn = con, statement = query_selectLocations)

locaties_sf <- locaties %>%
  mutate(locatie_type = ifelse(parent_id == -1,  "locatie", "sublocatie"),
         meetnet_type = ifelse(meetnet %in% c("Otter", "Gerande oeverspin", "Vliegend hert", "Roestbruine kniptor") | soortgroep == "mollusken", "inhaalslag", "meetnet"),
         type = ifelse(meetnet_type == "meetnet",
                       ifelse(is_sample == 1, "meetnetlocatie", "optionele locatie"),
                       ifelse(meetnet_type == "inhaalslag", "locatie inhaalslag", NA))) %>%
  select(soortgroep, meetnet, locatie, locatie_type, regio, is_active, is_sample, locatie_type, everything()) %>%
  mutate(geom = geom_text) %>%
  st_as_sf(wkt = "geom", crs = 4326)

locaties_hoofdlocatie <- locaties_sf %>%
  filter(locatie_type == "locatie") %>%
  arrange(soortgroep, meetnet, locatie)

namen_hoofdlocaties <- locaties_hoofdlocatie %>%
  st_drop_geometry() %>%
  mutate(geclaimd = ifelse(is.na(user_id), "nee", "ja"),
         geclaimd_door = str_c(first_name, last_name, sep = " ")) %>%
  select(meetnet, locatie, locatie_id = id,  geclaimd, geclaimd_door)

sublocations_transecten <- locaties_sf %>%
  filter(locatie_type == "sublocatie") %>%
  arrange(soortgroep, meetnet, locatie) %>%
  mutate(sectie_lijn = (substr(geom_text, 1, 4) == "LINE") | (substr(geom_text, 1, 9) == "MULTILINE")) %>%
  rename(sublocatie = locatie, locatie_id = parent_id) %>%
  left_join(namen_hoofdlocaties, by = c("meetnet", "locatie_id")) %>%
  arrange(soortgroep, meetnet, locatie, sublocatie) %>%
  filter(!is.na(locatie))

st_write(locaties_sf, "../raw/meetnetten_locaties.gpkg", layer = "locaties", driver = "GPKG", delete_layer = TRUE)
st_write(sublocations_transecten, "../raw/meetnetten_locaties.gpkg", layer = "transecten", driver = "GPKG", delete_layer = TRUE)
```

# Aantallen

## Algemeen

```{r}
query_aantallen <- "select PG.name as soortgroep
    , P.name as meetnet
    , L.name as locatie
    , L1.name as sublocatie
    , PR.name as protocol
    , V.id as visit_id
    , V.start_date as datum
    , SA.Not_Counted as niet_geteld
    , SA.is_complete as checklist
    , SA.Notes as opmerkingen
    , O.species_ID
    , SP.name as soort_nl
    , SP.scientific_name as soort_wet
    , PS.is_primary as primaire_soort
    , O.sample_id
    , O.sex as geslacht
    , O.id as observation_id
    , ACT.name as activiteit
    , LS.name as levensstadium
    , O.number_min as aantal
    , PSC.name as type_aantal
    , O.geom.STAsText() as geom_text
 from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_ID = P.ID
    left Outer join staging_Meetnetten.protocols_protocol PR on PR.id = V.protocol_id
    left outer join staging_Meetnetten.fieldwork_sample SA on SA.visit_ID = V.ID
    left outer join staging_Meetnetten.fieldwork_observation O on O.sample_ID = SA.ID
    left outer join staging_Meetnetten.protocols_scale PSC on O.scale_ID = PSC.ID
    left outer join staging_Meetnetten.Species_species SP on SP.ID = O.species_id
    left outer join staging_Meetnetten.species_activity ACT on ACT.id = O.activity_id
    left outer join staging_Meetnetten.species_lifestage LS on LS.id = O.life_stage_id
    left outer join staging_Meetnetten.Locations_location L ON L.ID = V.location_ID
    left outer Join staging_Meetnetten.Locations_location L1 on L1.ID = SA.location_id
    left outer join staging_Meetnetten.accounts_user U on U.ID = V.user_id
    left outer join staging_Meetnetten.projects_projectspecies PS on PS.species_ID = O.species_ID and PS.project_ID = P.ID
where 1=1
    and P.name <> 'Algemene Broedvogelmonitoring (ABV)'
    and P.name <> 'Algemene Vlindermonitoring'
    and P.name <> 'Vleermuizen - Wintertellingen'
    and SA.notes <> 'dummy sample'
    and PG.name <> 'planten'
    and V.validation_status <> -1 --afgekeurd
Order by PG.name
    , P.name
    , L.Name
    , V.start_date
    , L1.Name"

aantallen_orig <- dbGetQuery(con, query_aantallen)

aantallen_punt <- aantallen_orig %>%
  filter(str_detect(geom_text, "POINT")) %>%
  mutate(geom = geom_text) %>%
  st_as_sf(wkt = "geom_text", crs = 4326) %>%
  st_transform(31370)

aantallen_punt <- aantallen_punt  %>%
  mutate(x = st_coordinates(aantallen_punt)[, 1],
         y = st_coordinates(aantallen_punt)[, 2]) %>%
  st_drop_geometry() %>%
  select(-geom)

aantallen_overig <- aantallen_orig %>%
  filter(!str_detect(geom_text, "POINT") | is.na(geom_text)) %>%
  select(-geom_text)

aantallen_orig <- bind_rows(aantallen_punt,
                             aantallen_overig)

aantallen <- aantallen_orig %>%
  mutate(jaar = as.numeric(format(datum, "%Y")),
         doy = as.numeric(format(datum, "%j"))) %>%
  mutate(levensstadium = ifelse(levensstadium == "adult" & soortgroep == "libellen", "imago", levensstadium)) %>%
  select(soortgroep, meetnet, protocol, locatie, jaar, datum, doy, everything())

write_vc(aantallen, "aantallen", root = "../raw", sorting = c("soortgroep", "meetnet", "locatie", "visit_id", "sample_id", "observation_id"), strict = FALSE)

```
## Planten

```{r}
query_aantallen_planten <- "select O.id
    , PG.name as soortgroep
    , P.name as meetnet
    , L.name as locatie
    , PR.name as protocol
    , V.id as visit_id
    , V.start_date as datum
    , v.validation_status as validatie
    , v.track_geom.STAsText() as track_geom_text
    , SA.Not_Counted as niet_geteld
    , SA.Notes as opm
    , O.species_id
    , SP.name as soort_nl
    , SP.scientific_name as soort_wet
    , PS.is_primary as primaire_soort
    , O.sample_id
    , O.geom.STAsText() as geom_text
    , S.name as schaal
    , SC.code
    , O.number_min as aantal_min
    , O.number_max as aantal_max
    , SC.description as beschrijving_floroncode
    , u.first_name
    , u.last_name
 from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_ID = P.ID
    inner join staging_Meetnetten.protocols_protocol PR on PR.id = V.protocol_id
    inner join staging_Meetnetten.fieldwork_sample SA on SA.visit_ID = V.ID
    inner join staging_Meetnetten.fieldwork_observation O on O.sample_ID = SA.ID
    inner join staging_Meetnetten.Species_species SP on SP.ID = O.species_id
    inner join staging_Meetnetten.species_activity ACT on ACT.id = O.activity_id
    inner join staging_Meetnetten.species_lifestage LS on LS.id = O.life_stage_id
    inner join staging_Meetnetten.protocols_scalecode SC on SC.id = O.scale_code_id
    inner join staging_Meetnetten.protocols_scale S on S.id = O.scale_id
    inner join staging_Meetnetten.Locations_location L ON L.ID = V.location_ID
    inner Join staging_Meetnetten.Locations_location L1 on L1.ID = SA.location_id
    inner join staging_Meetnetten.accounts_user U on U.ID = V.user_id
    inner join staging_Meetnetten.projects_projectspecies PS on PS.species_ID = O.species_ID and PS.project_ID = P.ID
where 1=1
    and PG.name = 'planten'
Order by PG.name
    , P.name
    , L.Name
    , V.start_date
    , L1.Name"

aantallen_planten <- dbGetQuery(con, query_aantallen_planten) %>%
  mutate(puntlocatie = ifelse(is.na(geom_text), 0, 1),
         track = ifelse(is.na(track_geom_text), 0, 1))

aantallen_planten_puntlocaties <- aantallen_planten %>%
  filter(puntlocatie == 1) %>%
  mutate(waarnemer = str_c(first_name, " ", last_name)) %>%
  select(meetnet, protocol, locatie, datum,  soort_w = soort_wet, visit_id, waarnemer, validatie_bezoek = validatie, track, sample_id, schaal, code, beschrijving_floroncode, opm, geom = geom_text) %>%
  st_as_sf(wkt = "geom", crs = 4326)
  
aantallen_planten <- aantallen_planten %>%
  select(-geom_text, -track_geom_text)

st_write(aantallen_planten_puntlocaties,  "../raw/planten_puntlocaties", layer = "planten_puntlocaties", driver = "ESRI Shapefile", delete_layer = TRUE)
st_write(aantallen_planten_puntlocaties, "../raw/planten_puntlocaties.gpkg", layer = "planten_puntlocaties", driver = "GPKG", delete_layer = TRUE)
write_vc(aantallen_planten, "aantallen_planten", root = "../raw", sorting = c("soortgroep", "meetnet", "locatie", "visit_id", "sample_id"), strict = FALSE)
```


## ABV

```{r, eval = FALSE}
query_aantallen_abv <- "select PG.name as soortgroep
    , P.name as meetnet
    , L.name as locatie
    , L1.name as sublocatie
    , PR.name as protocol
    , V.id as visit_id
    , V.start_date as datum
    , SA.Not_Counted as niet_geteld
    , SA.is_complete as checklist
    , SA.Notes as opmerkingen
    , O.species_id
    , SP.name as soort_nl
    , SP.scientific_name as soort_wet
    , PS.is_primary as primaire_soort
    , O.sample_id
    , O.id as observation_id
    , O.number_min as aantal
 from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_ID = P.ID
    left Outer join staging_Meetnetten.protocols_protocol PR on PR.id = V.protocol_id
    left outer join staging_Meetnetten.fieldwork_sample SA on SA.visit_ID = V.ID
    left outer join staging_Meetnetten.fieldwork_observation O on O.sample_ID = SA.ID
    left outer join staging_Meetnetten.Species_species SP on SP.ID = O.species_id
    left outer join staging_Meetnetten.species_activity ACT on ACT.id = O.activity_id
    left outer join staging_Meetnetten.species_lifestage LS on LS.id = O.life_stage_id
    left outer join staging_Meetnetten.Locations_location L ON L.ID = V.location_ID
    left outer Join staging_Meetnetten.Locations_location L1 on L1.ID = SA.location_id
    left outer join staging_Meetnetten.accounts_user U on U.ID = V.user_id
    left outer join staging_Meetnetten.projects_projectspecies PS on PS.species_ID = O.species_ID and PS.project_ID = P.ID
where 1=1
    and P.name = 'Algemene Broedvogelmonitoring (ABV)'
    and V.validation_status <> -1 --afgekeurd
Order by PG.name
    , P.name
    , L.Name
    , V.start_date
    , L1.Name"

aantallen_abv <- dbGetQuery(con, query_aantallen_abv)

write_vc(aantallen_abv, "aantallen_abv", root = "../raw", sorting = c("soortgroep", "meetnet", "locatie", "visit_id", "sample_id", "observation_id", "soort_nl"), strict = FALSE)

```

## Vleermuizen wintertellingen

```{r, eval = FALSE}
query_aantallen_wintertellingen <- "select PG.name as soortgroep
    , P.name as meetnet
    , L.name as locatie
    , L1.name as sublocatie
    , PR.name as protocol
    , V.id as visit_id
    , V.start_date as datum
    , SA.Not_Counted as niet_geteld
    , SA.is_complete as checklist
    , SA.Notes as opmerkingen
    , O.species_id
    , SP.name as soort_nl
    , SP.scientific_name as soort_wet
    , PS.is_primary as primaire_soort
    , O.sample_id
    , O.id as observation_id
    , O.number_min as aantal
 from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_ID = P.ID
    left Outer join staging_Meetnetten.protocols_protocol PR on PR.id = V.protocol_id
    left outer join staging_Meetnetten.fieldwork_sample SA on SA.visit_ID = V.ID
    left outer join staging_Meetnetten.fieldwork_observation O on O.sample_ID = SA.ID
    left outer join staging_Meetnetten.Species_species SP on SP.ID = O.species_id
    left outer join staging_Meetnetten.species_activity ACT on ACT.id = O.activity_id
    left outer join staging_Meetnetten.species_lifestage LS on LS.id = O.life_stage_id
    left outer join staging_Meetnetten.Locations_location L ON L.ID = V.location_ID
    left outer Join staging_Meetnetten.Locations_location L1 on L1.ID = SA.location_id
    left outer join staging_Meetnetten.accounts_user U on U.ID = V.user_id
    left outer join staging_Meetnetten.projects_projectspecies PS on PS.species_ID = O.species_ID and PS.project_ID = P.ID
where 1=1
    and P.name = 'Vleermuizen - Wintertellingen'
    and V.validation_status <> -1 --afgekeurd
Order by PG.name
    , P.name
    , L.Name
    , V.start_date
    , L1.Name"

aantallen_wintertellingen <- dbGetQuery(con, query_aantallen_wintertellingen)

write_vc(aantallen_wintertellingen, "aantallen_wintertellingen", root = "../raw", sorting = c("soortgroep", "meetnet", "locatie", "visit_id", "sample_id", "observation_id", "soort_nl"), strict = FALSE)
```

## Hazelmuis nestbuizen

```{r}
query_aantallen_nb <- "select PG.name as soortgroep
    , P.name as meetnet
    , L.name as locatie
    , L1.name as sublocatie
    , PR.name as protocol
    , V.id as visit_id
    , V.start_date as datum
    , SA.Not_Counted as niet_geteld
    , SA.is_complete as checklist
    , SA.Notes as opmerkingen
    , O.species_id
    , SP.name as soort_nl
    , SP.scientific_name as soort_wet
    , PS.is_primary as primaire_soort
    , O.sample_id
    , O.sex as geslacht
    , O.id as observation_id
    , ACT.name as activiteit
    , LS.name as levensstadium
    , sc.name as observation_type
    , scc.code
    , scc.description
    , O.number_min as aantal
 from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_ID = P.ID
    left Outer join staging_Meetnetten.protocols_protocol PR on PR.id = V.protocol_id
    left outer join staging_Meetnetten.fieldwork_sample SA on SA.visit_ID = V.ID
    left outer join staging_Meetnetten.fieldwork_observation O on O.sample_ID = SA.ID
    left outer join staging_Meetnetten.Species_species SP on SP.ID = O.species_id
    left outer join staging_Meetnetten.species_activity ACT on ACT.id = O.activity_id
    left outer join staging_Meetnetten.species_lifestage LS on LS.id = O.life_stage_id
    left outer join staging_Meetnetten.Locations_location L ON L.ID = V.location_ID
    left outer Join staging_Meetnetten.Locations_location L1 on L1.ID = SA.location_id
    left outer join staging_Meetnetten.accounts_user U on U.ID = V.user_id
    left outer join staging_Meetnetten.projects_projectspecies PS on PS.species_ID = O.species_ID and PS.project_ID = P.ID
    left join staging_Meetnetten.protocols_scale sc on sc.id = o.scale_id
    left join staging_Meetnetten.protocols_scalecode scc on scc.id = o.scale_code_id
where 1=1
and v.project_id = 70 --Hazelmuis nestbuizen
Order by PG.name
    , P.name
    , L.Name
    , V.start_date
    , L1.Name"

aantal_hazelmuis_nestbuizen <- dbGetQuery(con, query_aantallen_nb)

aantal_hazelmuis_nestbuizen <- aantal_hazelmuis_nestbuizen %>%
  filter(!is.na(soort_nl)) %>%
  mutate(visit_id = as.character(visit_id))

write_vc(aantal_hazelmuis_nestbuizen, "aantal_hazelmuis_nestbuizen", root = "../raw", sorting = c("locatie", "sublocatie", "visit_id"), strict = FALSE)
```
## Gentiaanblauwtje

```{r}
query_aantallen_gb <- "select PG.name as soortgroep
    , P.name as meetnet
    , L.name as locatie
    , L1.name as sublocatie
    , PR.name as protocol
    , V.id as visit_id
    , V.start_date as datum
    , SA.Not_Counted as niet_geteld
    , SA.is_complete as checklist
    , SA.Notes as opmerkingen
    , O.species_id
    , SP.name as soort_nl
    , SP.scientific_name as soort_wet
    , PS.is_primary as primaire_soort
    , O.sample_id
    , O.sex as geslacht
    , LS.name as levensstadium
    , O.id as observation_id
    , plant.value as plant
    , stengel.value as stengel
    , Knop.value as knop
    , O.number_min as aantal
 from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_ID = P.ID
    left Outer join staging_Meetnetten.protocols_protocol PR on PR.id = V.protocol_id
    left outer join staging_Meetnetten.fieldwork_sample SA on SA.visit_ID = V.ID
    left outer join staging_Meetnetten.fieldwork_observation O on O.sample_ID = SA.ID
    left outer join staging_Meetnetten.Species_species SP on SP.ID = O.species_id
    left outer join staging_Meetnetten.species_activity ACT on ACT.id = O.activity_id
    left outer join staging_Meetnetten.species_lifestage LS on LS.id = O.life_stage_id
    left outer join staging_Meetnetten.Locations_location L ON L.ID = V.location_ID
    left outer Join staging_Meetnetten.Locations_location L1 on L1.ID = SA.location_id
    left outer join staging_Meetnetten.accounts_user U on U.ID = V.user_id
    left outer join staging_Meetnetten.projects_projectspecies PS on PS.species_ID = O.species_ID and PS.project_ID = P.ID
    left outer join (select OV.object_ID, OV.value
                    from staging_Meetnetten.fieldwork_observationvalue OV 
                    where OV.attribute_ID = 43)plant on plant.object_ID = O.ID
    left outer join (select OV.object_ID, OV.value
                    from staging_Meetnetten.fieldwork_observationvalue OV 
                    where OV.attribute_ID in (44,66))stengel on stengel.object_ID = O.ID
    left outer join (select OV.object_ID, OV.value
                    from staging_Meetnetten.fieldwork_observationvalue OV 
                    where OV.attribute_ID in (45,67))knop on knop.object_ID = O.ID
where 1=1
and P.name = 'Gentiaanblauwtje'
Order by PG.name
    , P.name
    , L.Name
    , V.start_date
    , L1.Name"

aantal_gb <- dbGetQuery(con, query_aantallen_gb)

aantal_gb <- aantal_gb %>%
  filter(!is.na(soort_nl)) %>%
  mutate(visit_id = as.character(visit_id),
         plant = as.numeric(plant),
         stengel = as.numeric(stengel),
         knop = as.numeric(knop)) %>%
  arrange(locatie, datum, visit_id, plant, stengel, knop)

write_vc(aantal_gb, "aantal_gentiaanblauwtje", root = "../raw", sorting = c("locatie", "visit_id", "plant", "stengel", "knop"), strict = FALSE)
```


# Covariabelen

```{r}
query_covariabelen_visit <- "Select P.Name as meetnet
    , PR.name as protocol
    , V.ID as visit_id
    , A.name as bezoekvariabele
    , case when C.value is null then VV.value else C.name end as waarde
    , U.name as eenheid
from staging_Meetnetten.Projects_project P
    INNER JOIN staging_Meetnetten.Fieldwork_visit V on V.project_ID = P.ID
    INNER JOIN staging_Meetnetten.Protocols_protocol PR on PR.ID = V.protocol_ID
    inner JOIN staging_Meetnetten.fieldwork_visitvalue VV on VV.object_ID = V.ID
    left outer JOIN staging_Meetnetten.model_attributes_attribute A on A.ID = VV.attribute_ID
    left outer Join staging_Meetnetten.model_attributes_unit U on U.id = A.unit_id
    LEFT Outer Join staging_Meetnetten.Model_attributes_choice C on C.Attribute_id = VV.attribute_id and cast(C.id as varchar(100)) = VV.value
Order by P.Name, PR.name, VV.object_ID"

query_covariabelen_sample <- "Select P.Name as meetnet
    , PR.name as protocol
    , V.ID as visit_id
    , SA.id as sample_id
    , A.name as bezoekvariabele
    , SV.value as waarde
    , U.name as eenheid
from staging_Meetnetten.Projects_project P
    INNER JOIN staging_Meetnetten.Fieldwork_visit V on V.project_ID = P.ID
    INNER JOIN staging_Meetnetten.Protocols_protocol PR on PR.ID = V.protocol_ID
    left outer join staging_Meetnetten.fieldwork_sample SA on SA.visit_ID = V.ID
    inner JOIN staging_Meetnetten.fieldwork_samplevalue SV on SV.object_ID = SA.ID
    left outer JOIN staging_Meetnetten.model_attributes_attribute A on A.ID = SV.attribute_ID
    left outer Join staging_Meetnetten.model_attributes_unit U on U.id = A.unit_id
    LEFT Outer Join staging_Meetnetten.Model_attributes_choice C on C.Attribute_id = SV.attribute_id and cast(C.id as varchar(100)) = SV.value
where 1=1
Order by P.Name, PR.name, SV.object_id"

covariabelen_visit <- dbGetQuery(con, query_covariabelen_visit)
covariabelen_sample <- dbGetQuery(con, query_covariabelen_sample)

write_vc(covariabelen_visit, "covariabele", root = "../raw", sorting = c("meetnet","visit_id"), strict = FALSE)
write_vc(covariabelen_sample, "covariabele_sample", root = "../raw", sorting = c("meetnet","visit_id", "sample_id"), strict = FALSE)
```
# Tracks

```{r}
query_tracks <- "select PG.name as soortgroep
    , P.name as meetnet
    , L.name as locatie
    , PR.name as protocol
    , V.id as visit_id
    , V.start_date as datum
    , v.source
    , v.validation_status as validatie
     , v.track_geom.STAsText() as track_geom_text
 from staging_Meetnetten.Projects_project P
    inner join staging_Meetnetten.projects_projectgroup PG on PG.id = P.group_id
    inner join staging_Meetnetten.fieldwork_visit V on V.project_ID = P.ID
    inner join staging_Meetnetten.protocols_protocol PR on PR.id = V.protocol_id
    inner join staging_Meetnetten.Locations_location L ON L.ID = V.location_ID
where 1=1
Order by PG.name
    , P.name
    , L.Name
    , V.start_date"

tracks <- dbGetQuery(con, query_tracks) %>%
  filter(!is.na(track_geom_text)) %>%
  filter(validatie != "-1") %>%
  rename(geom = track_geom_text) %>%
  st_as_sf(wkt = "geom", crs = 4326) 

tracks_planten <- tracks %>%
  filter(soortgroep == "planten")

```





