---
title: "Externe data meetnetten"
output: html_document
---

```{r}
library(leaflet)
library(sf)
library(git2rdata)
library(tidyverse)
library(units)
```

# Hamsterburchten

## Gevonden burchten

```{r}
burchten2016_sf <- read_sf("../data_extern/count_data/hamster", "Hamster_gevonden_burchten_2016_Lambert72_EPSG31370")

burchten2016 <- burchten2016_sf %>%
  mutate(datum = as.Date(OPMERKING, format = "%Y-%m-%d"),
         aantal = 1,
         x = st_coordinates(geometry)[, 1],
         y = st_coordinates(geometry)[, 2],
         opmerking = str_c("aantal pijpen = ", AANTALPIJP),
         soort_wet = "Cricetus cricetus",
         soort_nl = "Europese Hamster") %>%
  st_drop_geometry() %>%
    select(soort_wet, soort_nl, datum, aantal,  opmerking, x, y)

burchten2017_sf <- read_sf("../data_extern/count_data/hamster", "Hamsterburchten_2017_v29092017_Lambert72")

burchten2017 <- burchten2017_sf %>%
  rename(id_wnm = ID, soort_wet = Wetenschap, soort_nl = Naam, aantal = Aantal, opmerking = Toelichtin, hoofdteller = Waarnemer, zeker = Zeker) %>%
  mutate(datum = as.Date(Datum, format = "%d/%m/%Y"),
         x = st_coordinates(geometry)[, 1],
         y = st_coordinates(geometry)[, 2],
         zeker = ifelse(zeker == "Y", "ja",
                        ifelse(zeker == "N", "nee", NA))) %>%
  st_drop_geometry() %>%
  select(id_wnm, soort_wet, soort_nl, datum, aantal, zeker, hoofdteller, opmerking, x, y)

burchten2018_sf <- read_sf("../data_extern/count_data/hamster", "Hamsterburchten_2018_Meetnet-waarnemingen-ontdubbeld_Lambert72_31370_v2018-12-12")

burchten2018 <- burchten2018_sf %>%
  rename(id_wnm = id, soort_wet = naam_lat, soort_nl = naam_nl, opmerking = bijzonderh, hoofdteller = wnr) %>%
  mutate(datum = as.Date(datum, format = "%Y-%m-%d"),
         zeker = ifelse(zeker == "J", "ja",
              ifelse(zeker == "N", "nee", NA)),
         # opmerking = ifelse(!is.na(opmerking), 
         #                    str_c(opmerking, "; zeker = ", zeker),
         #                    str_c("zeker = ", zeker)),
         x = st_coordinates(geometry)[, 1],
         y = st_coordinates(geometry)[, 2]) %>%
  st_drop_geometry() %>%
  select(id_wnm, soort_wet, soort_nl, datum, aantal, zeker, hoofdteller, opmerking, x, y)

burchten2019_sf <- st_read("../data_extern/count_data/hamster", "Hamsterburchten_2019_Meetner-waarnemingen_v14012020_Lambert72")

burchten2019 <- burchten2019_sf %>%
  rename(id_wnm = id, soort_wet = naam_lat, soort_nl = naam_nl, opmerking = bijzonderh, hoofdteller = wnr) %>%
  mutate(datum = as.Date(datum, format = "%d-%m-%Y"),
         x = st_coordinates(geometry)[, 1],
         y = st_coordinates(geometry)[, 2]) %>%
  st_drop_geometry() %>%
  select(id_wnm, soort_wet, soort_nl, datum, aantal, hoofdteller, opmerking, x, y)

burchten2020_sf <- st_read("../data_extern/count_data/hamster", "Hamsterburchten_2020_meetnet_waarnemingen_Lambert72_ontdubbeld")

burchten2020 <- burchten2020_sf %>%
  rename(id_wnm = id, soort_wet = naam_lat, soort_nl = naam_nl, opmerking = bijzonderh, hoofdteller = wnr, zeker = Zeker) %>%
  mutate(datum = as.Date(datum, format = "%d-%m-%Y"),
         zeker = ifelse(zeker == 1, "ja",
              ifelse(zeker == 0, "nee", NA)),
         x = st_coordinates(geometry)[, 1],
         y = st_coordinates(geometry)[, 2]) %>%
  st_drop_geometry() %>%
  select(id_wnm, soort_wet, soort_nl, datum, aantal, zeker, hoofdteller, opmerking, x, y)


burchten_all <- bind_rows(burchten2016,
                          burchten2017,
                          burchten2018,
                          burchten2019,
                          burchten2020) %>%
  mutate(meetnet = "Hamster",
         protocol = "Hamster - Burcht",
         locatie = "Widooie")
 
burchten_all_sf <- burchten_all %>%
  st_as_sf(coords = c("x", "y"), crs = 31370)                         
```

## Onderzochte percelen

```{r}
percelen_2020_sf_orig <- read_sf("../data_extern/count_data/hamster", "Hamster_percelen_onderzocht_2020_v05012020_Lambert72")

percelen_2020_sf <- percelen_2020_sf_orig %>%
  rename(id_perceel = id, aantal_tellers = X.Tellers, opmerking = Bruchten, gewas = Gewas, oppervlakte_ha = opp..ha.) %>%
  mutate(meetnet = "Hamster",
         datum = as.Date(VisitDate, format = "%d/%m/%Y"),
         type_telling = ifelse(datum > as.Date("2020-06-01"), "zomer", "winter")) %>%
  select(meetnet, id_perceel, datum, type_telling, aantal_tellers, gewas, oppervlakte_ha, opmerking)

oppervlakte_onderzocht <- percelen_2020_sf %>%
  st_drop_geometry() %>%
  group_by(type_telling) %>%
  summarise(oppervlakte_ha_totaal = sum(oppervlakte_ha),
            n_bezoeken = n_distinct(datum)) %>%
  ungroup()
```




```{r}
locaties_hamster <- read_sf("../raw/meetnetten_locaties.gpkg", "locaties") %>%
  filter(meetnet == "Hamster") %>%
  select(locatie)

```

```{r}
burchten_all_sf %>%
  st_transform(crs = 4326) %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers() %>%
  addPolygons(data = locaties_hamster)
```


# Das

```{r}
das_orig <- read.csv2("../data_extern/count_data/das/meetnet_das_2016_2020.csv")

das <- das_orig %>%
  mutate(meetnet = "Das",
         protocol = "Das - Burcht",
         soort_nl = "Das",
         soort_wet = "Meles meles", 
         locatie = str_c("burcht_", burchtID),
         datum = as.Date(str_c("01-01-", Jaar), format = "%d-%m-%Y"),
         aantal = ifelse(status == "Verdwenen", 0, 1)
         ) %>%
  select(meetnet, protocol, locatie, datum, jaar = Jaar, soort_nl, soort_wet, aantal, status, bewoning, opmerking = Gebied) %>%
  gather(status, bewoning, key = "covariabele", value = "waarde")
  
overzicht_das_jaar <- das %>%
  group_by(meetnet, jaar, locatie, opmerking) %>%
  summarise(n_bezoeken = n_distinct(datum)) %>%
  ungroup() %>%
  group_by(meetnet, jaar, opmerking) %>%
  summarise(n_bezoeken = sum(n_bezoeken),
            n_locaties = n_distinct(locatie)) %>%
  ungroup()

overzicht_das_cyclus2 <- das %>%
  filter(jaar >= 2019) %>%
  group_by(meetnet, locatie, opmerking) %>%
  summarise(n_bezoeken = n_distinct(datum)) %>%
  ungroup() %>%
  group_by(meetnet,  opmerking) %>%
  summarise(n_bezoeken = sum(n_bezoeken),
            n_locaties = n_distinct(locatie)) %>%
  ungroup()
```

# Samenvoegen burchten

```{r}
data_extern <- burchten_all %>%
  bind_rows(das)

visit_ids <- data_extern %>%
  distinct(meetnet, locatie, datum) %>%
  mutate(visit_id = str_c("extern_", 1:n_distinct(meetnet, locatie, datum)))

data_extern_burchten <- data_extern %>%
  left_join(visit_ids, by = c("meetnet", "locatie", "datum")) %>%
  select(meetnet, protocol, locatie, visit_id, datum, everything())
```

# Gerande oeverspin

```{r}

data_oeverspinnen_2019 <- read.csv2("../data_extern/count_data/gerande_oeverspin/oeverspinnen.csv", stringsAsFactors = FALSE) %>%
  filter(lon != "onbekend") %>%
  select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed) %>%
  mutate(id = as.character(id),
         datum = as.Date(datum, format = "%Y-%m-%d"))

data_oeverspinnen_2018 <- read.csv2("../data_extern/count_data/gerande_oeverspin/Dolomedes_SamenvattendeTabel_2018.csv", stringsAsFactors = FALSE) %>%
    select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
    mutate(id = as.character(id),
         datum = as.Date(datum, format = "%d/%m/%Y"))

data_oeverspinnen_tot2017 <- read_sf("../data_extern/count_data/gerande_oeverspin","Dolomedes_exportWnBe_23.03.2017_InternGebruik_Lambert1972") %>%
  select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed) %>%
  mutate(id = as.character(id),
         datum = as.Date(datum, format = "%Y-%m-%d")) %>%
  st_drop_geometry()

data_oeverspinnen_2020 <- read.csv2("../data_extern/count_data/gerande_oeverspin/GerandeOeverspin_wbe_2020.csv") %>%
    select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
    mutate(id = as.character(id),
         datum = as.Date(datum, format = "%d/%m/%Y"))

data_oeverspinnen <- bind_rows(data_oeverspinnen_tot2017,
                           data_oeverspinnen_2018,
                           data_oeverspinnen_2019,
                           data_oeverspinnen_2020) %>%
  mutate(validatie = ifelse(str_detect(status, "Goedgekeurd"), "goedgekeurd", "niet beoordeeld")) %>%
  filter(!is.na(x))

pot_leefgebied <- read_sf(dsn = "../data_extern/sampleframe/GerandeOeverspin_Lambert1972_versie2017-03-31", "GerandeOeverspin_Lambert1972_versie2017-03-31") %>%
  select(locatie = Naam)

data_oeverspinnen_sf <- data_oeverspinnen %>%
  st_as_sf(coords = c("x", "y"), crs = 31370) %>%
  st_join(pot_leefgebied, join = st_nearest_feature) %>%
  group_by(id) %>%
  mutate(dist = min(st_distance(geometry, pot_leefgebied))) %>%
  ungroup()

data_oeverspinnen <- data_oeverspinnen_sf %>%
  st_drop_geometry() %>%
  mutate(x = st_coordinates(data_oeverspinnen_sf)[, 1],
         y = st_coordinates(data_oeverspinnen_sf)[, 2],
         dist_to_pot_leefgebied = round(drop_units(dist), 0),
         locatie = ifelse(dist_to_pot_leefgebied > 250, NA, locatie)) %>%
  select(-dist) %>%
  mutate(jaar = as.numeric(format(datum, "%Y")),
         meetnet = "Gerande oeverspin") %>% 
  select(meetnet, jaar, locatie, gebied, datum, id, everything())
  

```
# Mollusken

```{r}
data_mollusken_2020 <- read.csv2("../data_extern/count_data/mollusken/P-CO-000385_Mollusken_wbe_2020_Dump20201201__ALLES_UNIEK.csv", stringsAsFactors = FALSE) %>%
  select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
  mutate(id = as.character(id),
         datum = as.Date(datum, format = "%Y-%m-%d"),
         naam_nl = ifelse(naam_nl == "Zegge-korfslak", "Zeggekorfslak", naam_nl))

data_mollusken_2019 <- read_sf(dsn = "../data_extern/count_data/mollusken", layer = "Export_waarnemingen_2019_molluskenmeetnetten") %>%
  st_drop_geometry() %>%
  select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
  mutate(id = as.character(id),
         datum = as.Date(datum, format = "%d-%m-%Y"))

data_mollusken_2016_2018 <- read_sf(dsn = "../data_extern/count_data/mollusken", layer = "Mollusken 2016-2018-10-30 export wnbe") %>%
  st_drop_geometry() %>%
  select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
  mutate(id = as.character(id),
         datum = as.Date(datum, format = "%Y-%m-%d"))

data_mollusken <- bind_rows(data_mollusken_2016_2018,
                           data_mollusken_2019,
                           data_mollusken_2020) %>%
  mutate(validatie = ifelse(str_detect(status, "Goedgekeurd"), "goedgekeurd", "niet beoordeeld"),
         meetnet = naam_nl) %>%
  filter(!is.na(x))

# locaties_mollusken_actief_sf <- read_sf("../raw/meetnetten_locaties.gpkg", "locaties") %>%
#   filter(soortgroep == "mollusken") %>%
#   filter(is_active) %>%
#   select(meetnet, locatie) %>%
#   st_transform(crs = 31370) 

pot_leefgebied_zeggekorfslak <- read_sf(dsn = "../data_extern/sampleframe/Zeggekorfslak_Lambert1972_versie2018-03-14", "Zeggekorfslak_Lambert1972_versie2018-03-14") %>%
  select(meetnet = Meetnet, locatie = Naam)

pot_leefgebied_platte_schijfhoorn <- read_sf(dsn = "../data_extern/sampleframe/PlatteSchijfhoren_Lambert1972_versie2018-03-14", "PlatteSchijfhoren_Lambert1972_versie2018-03-14") %>%
  select(meetnet = Meetnet, locatie = Naam) %>%
  mutate(meetnet = "Platte schijfhoren")

pot_leefgebied_nauwe_korfslak <- read_sf(dsn = "../data_extern/sampleframe/NauweKorfslak_Lambert1972_versie2018-03-14", "NauweKorfslak_Lambert1972_versie2018-03-14") %>%
  select(meetnet = Meetnet, locatie = Naam) %>%
  mutate(meetnet = "Nauwe korfslak")

pot_leefgebied_bataafse_stroommossel <- read_sf(dsn = "../data_extern/sampleframe/BataafseStroommossel_Lambert1972_versie2018-03-14", "BataafseStroommossel_Lambert1972_versie2018-03-14") %>%
  select(meetnet = Meetnet, locatie = Naam) %>%
  mutate(meetnet = "Bataafse stroommossel")

pot_leefgebied_mollusken <- bind_rows(
  pot_leefgebied_zeggekorfslak,
  pot_leefgebied_platte_schijfhoorn,
  pot_leefgebied_nauwe_korfslak,
  pot_leefgebied_bataafse_stroommossel
)

data_mollusken_by_meetnet <- data_mollusken %>%
  st_as_sf(coords = c("x", "y"), crs = 31370) %>%
  group_by(meetnet) %>%
  nest()

closest_location_actief <- function(meetnet_select, observations) {
  
  locations_meetnet <- pot_leefgebied_mollusken %>%
    filter(meetnet == meetnet_select )
  
  observations_result <- observations %>%
    st_join(locations_meetnet, join = st_nearest_feature) %>%
    group_by(id) %>%
    mutate(dist = min(drop_units(st_distance(geometry, locations_meetnet))),
           dist = round(dist, 0)) %>%
    ungroup() %>%
    dplyr::select(-meetnet) %>%
    st_drop_geometry() %>%
    mutate(x = st_coordinates(observations)[,1],
           y = st_coordinates(observations)[,2])
  
  return(observations_result)
            
}

data_mollusken_by_meetnet <- data_mollusken_by_meetnet %>%
  mutate(data_locations_actief = map2(meetnet, data, closest_location_actief))

data_mollusken_locaties <- data_mollusken_by_meetnet %>%
  select(data_locations_actief) %>%
  unnest(data_locations_actief) %>%
  mutate(locatie = ifelse(dist > 500, NA, locatie)) %>%
  rename(dist_to_pot_leefgebied = dist) %>%
  mutate(jaar = as.numeric(format(datum, "%Y"))) %>%
  select(meetnet, jaar, locatie, gebied, datum, id, everything())

```

# Roestbruine kniptor

```{r}

data_roestbruine_kniptor_2020 <- read.csv2("../data_extern/count_data/roestbruine_kniptor/RoestbrKniptor_wbe_2020.csv", stringsAsFactors = FALSE) %>%
  filter(lon != "onbekend") %>%
  select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
  mutate(id = as.character(id),
         datum = as.Date(datum, format = "%d/%m/%Y"))

data_roestbruine_kniptor_2019 <- read_sf("../data_extern/count_data/roestbruine_kniptor", "Roestbruine_kniptor_waarnemingen_2019") %>%
    select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
    mutate(id = as.character(id),
         datum = as.Date(datum, format = "%Y-%m-%d")) %>%
  st_drop_geometry()

data_roestbruine_kniptor_2018 <- read_sf("../data_extern/count_data/roestbruine_kniptor", "Roestbruine kniptor waarnemingen export 2018-12") %>%
    select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
    mutate(id = as.character(id),
         datum = as.Date(datum, format = "%Y-%m-%d")) %>%
  st_drop_geometry()

data_roestbruine_kniptor_2020 <- read.csv2("../data_extern/count_data/gerande_oeverspin/GerandeOeverspin_wbe_2020.csv") %>%
    select(id, naam_nl, naam_lat, datum, gebied, status, x, y, aantal, gedrag, kleed, waarnemer = wnr) %>%
    mutate(id = as.character(id),
         datum = as.Date(datum, format = "%d/%m/%Y"))

data_roestbruine_kniptor <- bind_rows(data_roestbruine_kniptor_2018,
                           data_roestbruine_kniptor_2019,
                           data_roestbruine_kniptor_2020) %>%
  mutate(validatie = ifelse(str_detect(status, "Goedgekeurd"), "goedgekeurd", "niet beoordeeld")) %>%
  filter(!is.na(x))

locaties_roestbruine_kniptor_sf <- read_sf("../raw/meetnetten_locaties.gpkg", "locaties") %>%
  filter(meetnet == "Roestbruine kniptor") %>%
  select(meetnet, locatie, is_active) %>%
  st_transform(crs = 31370)

data_roestbruine_kniptor_sf <- data_roestbruine_kniptor %>%
  st_as_sf(coords = c("x", "y"), crs = 31370) %>%
  st_join(locaties_roestbruine_kniptor_sf, join = st_nearest_feature) %>%
  group_by(id) %>%
  mutate(dist = min(st_distance(geometry, locaties_roestbruine_kniptor_sf))) %>%
  ungroup()

data_roestbruine_kniptor <- data_roestbruine_kniptor_sf %>%
  st_drop_geometry() %>%
  mutate(x = st_coordinates(data_roestbruine_kniptor_sf)[, 1],
         y = st_coordinates(data_roestbruine_kniptor_sf)[, 2],
         dist_to_pot_leefgebied = round(drop_units(dist), 0),
         locatie = ifelse(dist_to_pot_leefgebied > 250, NA, locatie),
         is_active = ifelse(is.na(locatie), NA, is_active)) %>%
  select(-dist) %>%
  mutate(jaar = as.numeric(format(datum, "%Y")),
         meetnet = "Roestbruine kniptor") %>% 
  select(meetnet, jaar, locatie, locatie_actief = is_active, gebied, datum, id, everything())
  
```



# Export

```{r}
write_vc(data_extern_burchten, "data_burchten", "../processed")
write_vc(data_oeverspinnen, "data_oeverspinnen", "../processed", strict = FALSE)
write_vc(data_mollusken_locaties, "data_mollusken", "../processed", strict = FALSE)
write_vc(data_roestbruine_kniptor, "data_roestbruine_kniptor", "../processed", strict = FALSE)
```

