---
title: "Plantendata 2020"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
library(git2rdata)
library(units)
library(purrr)
library(readxl)
```


```{r}
planten_2020_orig <- read_excel("../data_extern/count_data/planten/Planten_wbe_Meetnetten_exportfinaal_aangepast.xlsx")

planten_meetvariabelen <- read.csv2("../data_extern/count_data/Planten/PlantenMeetvariabelen.csv") %>%
  rename(meetnet = Meetnet)

data_ruw_2020 <- planten_2020_orig %>%
  mutate(naam_nl = ifelse(naam_lat == "Gentianella amarella subsp. uliginosa", "Duingentiaan", naam_nl),
         naam_nl = ifelse(naam_lat == "Gentianella uliginosa", "Duingentiaan", naam_nl),
         naam_nl = ifelse(naam_lat == "Orchis morio", "Harlekijn", naam_nl),
         naam_nl = ifelse(naam_lat == "Diphasiastrum tristachyum", "Kleine wolfsklauw", naam_nl)
         ) %>% 
  mutate(datum = ifelse(id == 205241481, "2020-06-15", datum))%>%
  select(id, meetnet = naam_nl,  datum, invoerdatum,  x, y, aantal, floroncode = Floroncode, typewaarneming, waarnemer = wnr, status, locatie_np = Locatie, ingevoerd = Meetnet, opm = bijzonderheden)%>%
  mutate(datum = as.Date(datum, format = "%Y-%m-%d"),
         jaar = as.numeric(format(as.Date(datum, format = "%Y-%m-%d"),"%Y")),
         uitvoerder = "vrijwilligers",
         brondatabank = "waarnemingen.be",
         id =as.character(id)) %>%
  left_join(planten_meetvariabelen, by = "meetnet") %>%
  rename(meetvariabele = Meetvariabele) %>%
  mutate(floroncode = ifelse(floroncode == "0" & aantal > 0, NA, floroncode),
          floroncode_ingevoerd = ifelse(floroncode %in% c("A", "B", "C", "D", "E", "F", "0"), "Ja", "Nee"),
          floroncode = ifelse(floroncode %in% c("A", "B", "C", "D", "E", "F", "0"),
                                    floroncode,
                                    ifelse(meetvariabele == "Aantal" | aantal == 0, 
                                           ifelse(aantal == 0, "0",
                                           ifelse(aantal == 1, "A",
                                           ifelse(aantal < 6, "B",
                                           ifelse(aantal < 26, "C",
                                           ifelse(aantal < 51, "D",
                                           ifelse(aantal < 501, "E","F")))))),
                                           NA))) %>%
  mutate(x_coord = x, y_coord = y) %>%
  filter(!is.na(x)) %>%
  st_as_sf(coords = c("x", "y"), crs = 31370)

```



```{r}

locaties_planten_actief_sf <- st_read("../raw/meetnetten_locaties.gpkg", "locaties") %>%
  filter(soortgroep == "planten") %>%
  filter(is_active) %>%
  mutate(locatie = as.character(locatie),
         meetnet = as.character(meetnet)) %>%
    mutate(locatie = str_replace(locatie, "\u0091", "'"),
         locatie = str_replace(locatie, "\u0096", "-")) %>%
  select(meetnet, locatie) %>%
  st_transform(crs = 31370) 

data_extern_by_meetnet <- data_ruw_2020 %>%
  group_by(meetnet) %>%
  nest()

closest_location_actief <- function(meetnet_select, observations) {
  
  locations_meetnet <- locaties_planten_actief_sf %>%
    filter(meetnet == meetnet_select )
  
  observations_result <- observations %>%
    st_join(locations_meetnet, join = st_nearest_feature) %>%
    group_by(id) %>%
    mutate(dist = min(drop_units(st_distance(geometry, locations_meetnet))),
           dist = round(dist, 0)) %>%
    ungroup() %>%
    dplyr::select(-meetnet) %>%
    st_drop_geometry()
  
  return(observations_result)
            
}

data_extern_by_meetnet <- data_extern_by_meetnet %>%
  mutate(data_locations_actief = map2(meetnet, data, closest_location_actief))

data_extern_locaties <- data_extern_by_meetnet %>%
  select(data_locations_actief) %>%
  unnest(data_locations_actief) %>%
  mutate(locatie = ifelse(dist > 500, NA, locatie),
         dist = ifelse(dist > 500, NA, dist),
         datum = as.Date(datum, format = "%Y-%m-%d"))

check <- data_extern_locaties %>%
  filter(floroncode_ingevoerd == "Ja") %>%
  mutate(naam_controle = locatie == locatie_np)

n_distinct(check$locatie)

locaties_planten_inactief_sf <- st_read("../raw/meetnetten_locaties.gpkg", "locaties") %>%
  filter(soortgroep == "planten") %>%
  filter(!is_active) %>%
  mutate(locatie_inactief = as.character(locatie),
         meetnet = as.character(meetnet)) %>%
    mutate(locatie_inactief = str_replace(locatie_inactief, "\u0091", "'"),
         locatie_inactief = str_replace(locatie_inactief, "\u0096", "-")) %>%
  select(meetnet, locatie_inactief) %>%
  st_transform(crs = 31370) 

closest_location_inactief <- function(meetnet_select, observations) {
  
  locations_meetnet <- locaties_planten_inactief_sf %>%
    filter(meetnet == meetnet_select )
  
  observations_result <- observations %>%
    st_join(locations_meetnet, join = st_nearest_feature) %>%
    group_by(id) %>%
    mutate(dist_inactief = min(drop_units(st_distance(geometry, locations_meetnet))),
           dist_inactief = round(dist_inactief, 0)) %>%
    ungroup() %>%
    dplyr::select(-meetnet) %>%
    st_drop_geometry()
  
  return(observations_result)
            
}

data_extern_locaties_inactief <- data_extern_by_meetnet %>%
  mutate(data_locations_inactief =  map2(meetnet, data, closest_location_inactief)) %>% 
  select(data_locations_inactief) %>%
  unnest(data_locations_inactief)

data_extern_locaties_inactief <- data_extern_locaties_inactief %>%
  select(meetnet, id, locatie_inactief, dist_inactief)

data_extern_locaties2 <- data_extern_locaties %>%
  left_join(data_extern_locaties_inactief, by = c("id", "meetnet")) %>%
    mutate(locatie_inactief = ifelse(dist_inactief > 500, NA, locatie_inactief),
         dist_inactief = ifelse(dist_inactief > 500, NA, dist_inactief))
```

```{r,eval=FALSE}
testje <- planten_2020_orig %>%
  st_as_sf(coords = c("x", "y"), crs =31370) %>%
  st_transform(crs = 4326)

locaties_meetnet
  
```



```{r}

bezoeken_planten <- read_vc("bezoeken", "../raw") %>%
  filter(soortgroep == "planten") %>%
    mutate(locatie = ifelse(locatie == "Goor <U+0096> Asbroek (d5-16-34)", "Goor - Asbroek (d5-16-34)", locatie),
           locatie = ifelse(locatie == "<U+0091>s Hertogenheide (d5-45-24)", "'s Hertogenheide (d5-45-24)", locatie),
           locatie = ifelse(locatie == "Goorke <U+0096> Rode Del (b6-43-31)", "Goorke - Rode Del (b6-43-31)", locatie)) %>%
  left_join(locaties_planten_actief_sf, by = c("meetnet", "locatie")) %>%
  select(meetnet, locatie, datum, visit_id)

data_waarnemingen <- data_extern_locaties2 %>%
  left_join(bezoeken_planten, by = c("meetnet", "locatie", "datum")) %>%
  rename(afstand_tot_locatie = "dist") %>%
  mutate(bron = "waarenmingen.be",
         schaal = ifelse(meetvariabele == "Aantal", "aantal (Floron)", "oppervlakte (Floron")) 

aantallen_waarnemingen_mn <- data_waarnemingen %>%
  #filter(jaar == 2020) %>%
  filter(floroncode_ingevoerd == "Ja") %>%
  filter(!is.na(locatie)) %>%
  filter(!is.na(visit_id)) %>%
  select(bron, meetnet, locatie, afstand_tot_locatie, jaar, datum, waarnemer, id_wnm = id, code = floroncode,  schaal , aantal, x =x_coord, y = y_coord, visit_id, opm)

aantallen_waarnemingen_extra <- data_waarnemingen %>%
  filter((floroncode_ingevoerd == "Nee") | (is.na(locatie))) %>%
  select(bron, meetnet, locatie, afstand_tot_locatie, jaar, datum, waarnemer, id_wnm = id, code = floroncode,  schaal, aantal, x = x_coord, y = y_coord, visit_id, opm)

write_vc(data_waarnemingen, file = "data_plantenmeetnetten_2020", root = "../processed", strict = FALSE)

write.csv2(aantallen_waarnemingen_mn, file = "../processed/data_plantenmeetnetten_migratie2020.csv", row.names = FALSE, , na = "")
```

## Waarnemingen zonder bezoeken

```{r}

controle_bezoeken <- data_waarnemingen %>%
  filter(floroncode_ingevoerd == "Ja") %>%
  filter(is.na(visit_id)) %>%
  select(id, meetnet, locatie, locatie_inactief, locatie_np, datum, floroncode, x_coord, y_coord, waarnemer)

write.csv2(controle_bezoeken, "../output/wnm_planten_zonderbezoeken_2020_versie2021-02-25.csv")
```

## Data voor oude bezoeken

```{r}

bezoeken_locatie_incatief <- bezoeken_planten %>%
  anti_join(locaties_planten_actief_sf, by = c("meetnet", "locatie")) %>%
  rename(locatie_inactief = locatie, visit_id_locatie_inactief = visit_id)

aantallen_planten_visit_id <- read_vc("aantallen_planten", "../raw") %>%
  filter(validatie != -1) %>%
  group_by(visit_id) %>%
  summarise(puntlocaties_ingevoerd = n() > 0) %>%
  ungroup()

data_oude_bezoeken <- data_waarnemingen %>%
  filter(jaar < 2020) %>%
  filter(floroncode_ingevoerd == "Ja") %>% 
  left_join(bezoeken_locatie_incatief, by = c("meetnet", "locatie_inactief", "datum")) %>%
  left_join(aantallen_planten_visit_id, by = c("visit_id")) %>%
  mutate(match_bezoek_mn = !is.na(visit_id) | !is.na(visit_id_locatie_inactief),
         puntlocatie_ingevoerd = !is.na(puntlocaties_ingevoerd)) %>%
  select(meetnet, locatie, locatie_inactief, locatie_np, id_wnm = id, visit_id, visit_id_locatie_inactief ,puntlocatie_ingevoerd,  match_bezoek_mn,  datum, invoerdatum, floroncode, x_coord, y_coord, waarnemer)

write.csv2(data_oude_bezoeken, "../output/oude_bezoeken_migratie2021.csv")
```


## Bezoeken zonder waarnemingen

```{r}
aantallen_planten_visit_id <- read_vc("aantallen_planten", "../raw") %>%
  filter(puntlocatie == 1) %>%
  filter(validatie != -1) %>%
  group_by(meetnet, locatie, datum, visit_id, track) %>%
  summarise(n_puntlocaties = n()) %>%
  ungroup()

bezoeken_planten_2020_zonderdata <- read_vc("bezoeken", "../raw") %>%
    filter(validatie != -1) %>%
    filter(soortgroep == "planten") %>%
  filter(jaar == 2020) %>%
  filter(! visit_id %in% data_waarnemingen$visit_id) %>%
  filter(! visit_id %in% aantallen_planten_visit_id$visit_id) %>%
  select(meetnet, locatie, datum, hoofdteller, notes)

write.csv2(bezoeken_planten_2020_zonderdata, "../output/bezoeken_planten_zonderwnm_2020.csv")
```

## Alle data voor 2020

```{r}
aantallen_planten_meetnetten <- read_sf(dsn = "../raw/planten_puntlocaties.gpkg", "planten_puntlocaties") %>%
  mutate(jaar = as.numeric(format(datum, "%Y"))) %>%
  st_transform(crs = 31370) %>%
  filter(jaar == 2020) %>%
  filter(validatie_bezoek != -1) %>%
  mutate(bron = "meetnetten.be",
         afstand_tot_locatie = 0) %>%
  select(-soort_w, -beschrijving_floroncode, -protocol, -sample_id, -validatie_bezoek)

aantallen_meetnetten <- aantallen_planten_meetnetten %>%
  st_drop_geometry() %>%
  mutate(x = st_coordinates(aantallen_planten_meetnetten)[, 1],
         y = st_coordinates(aantallen_planten_meetnetten)[, 2])

aantallen_planten <- bind_rows(aantallen_waarnemingen_mn,
                               aantallen_meetnetten) %>%
  arrange(meetnet, locatie, bron)

write.csv2(aantallen_planten, "../processed/data_planten_2020.csv", row.names = FALSE, na = "")

write.csv2(aantallen_waarnemingen_extra, "../processed/data_planten_2020_extra.csv", row.names = FALSE, na = "")
```

## Alle data tussen 2016 en 2020

```{r}
aantallen_planten_meetnetten <- read_sf(dsn = "../raw/planten_puntlocaties.gpkg", "planten_puntlocaties") %>%
  mutate(jaar = as.numeric(format(datum, "%Y"))) %>%
  st_transform(crs = 31370) %>%
  filter(validatie_bezoek != -1) %>%
  mutate(bron = "meetnetten.be",
         afstand_tot_locatie = 0) %>%
  select(-soort_w, -beschrijving_floroncode, -protocol, -sample_id, -validatie_bezoek)

aantallen_meetnetten <- aantallen_planten_meetnetten %>%
  st_drop_geometry() %>%
  mutate(x = st_coordinates(aantallen_planten_meetnetten)[, 1],
         y = st_coordinates(aantallen_planten_meetnetten)[, 2])

aantallen_planten <- bind_rows(aantallen_waarnemingen_mn,
                               aantallen_meetnetten) %>%
  arrange(meetnet, locatie, bron)

write.csv2(aantallen_planten, "../processed/data_planten_2016_2020.csv", row.names = FALSE, na = "")

```
