---
title: "update_metadata"
output: html_document
---

```{r}
library(tidyverse)
library(INBOtheme)
library(sf)
library(git2rdata)
library(conflicted)
conflicts_prefer(dplyr::filter())
```

## Read file with monitoring scheme characteristics that are not available in meetnetten.be

```{r}
metadata_file <- read_csv2("../metadata/meetnetkarakteristieken.csv")
```

## Derive characteristics from meetnetten.be data

```{r}

locaties <- st_read("../raw/meetnetten_locaties.gpkg",
                    "locaties", quiet = TRUE)

bezoeken <- read_vc(file = "bezoeken", root = "../raw")
taken <- read_vc(file = "taken", root = "../raw")
werkpakketten <- read_vc(file = "werkpakketten", root = "../raw")

# karakteristieken locaties
locaties_metadata <- locaties %>%
  st_drop_geometry() %>%
  filter(locatie_type == "locatie") %>%
  distinct(meetnet, locatie, is_active, is_sample) %>%
  mutate(is_sample_history = is_sample | (!is_active)) #huidige en historische meetnetlocaties

# aantal locaties per meetnet
meetnetten_n_locaties <- locaties %>%
  st_drop_geometry() %>%
  filter(locatie_type == "locatie") %>%
  filter(is_active) %>%
  group_by( meetnet, is_sample) %>%
  summarise(n_locaties = n()) %>%
  ungroup()

# telperiodes
telperiodes_taak <- taken %>%
  filter(jaar == 2023) %>%
  select(soortgroep, meetnet, protocol, jaar, taak_start, taak_end) %>%
  unique() %>%
  group_by(meetnet, protocol) %>%
  mutate(periode = rank(taak_start)) %>%
  ungroup() %>%
  mutate(generatie = ifelse(meetnet %in% c("Argusvlinder", "Klaverblauwtje", "Bruin dikkopje"),
                            str_c("generatie", periode),
                            "generatie1"))

telperiodes_taak <- telperiodes_taak %>%
  group_by(soortgroep, meetnet, protocol, generatie) %>%
  summarise(start_telperiode = min(taak_start),
            einde_telperiode = max(taak_end)) %>%
  ungroup()

temp <- bezoeken %>%
  filter(jaar >= 2018) %>%
  distinct(soortgroep, meetnet, protocol) %>%
  bind_rows(tibble(soortgroep = "reptielen",
                   meetnet = "Gladde slang",
                   protocol = "Gladde slang - Telling onder platen"))

telperiodes_wp <- werkpakketten %>%
  group_by(meetnet) %>%
  filter(jaar == max(jaar)) %>%
  ungroup() %>%
  filter(!meetnet %in% telperiodes_taak$meetnet) %>%
  select(meetnet, start_telperiode = wp_start, einde_telperiode = wp_end) %>%
  unique() %>% 
  inner_join(temp, by = "meetnet") %>%
  filter(meetnet != "Vroedmeesterpad")

telperiodes_metadata <- metadata_file %>%
  filter(!meetnet %in% telperiodes_taak$meetnet) %>%
  filter(!meetnet %in% telperiodes_wp$meetnet) %>%
  mutate(start_telperiode = as.Date(start_telperiode, format = "%d/%m/%Y"),
         einde_telperiode = as.Date(einde_telperiode, format = "%d/%m/%Y")) %>%
  select(meetnet, protocol, start_telperiode, einde_telperiode) %>%
  unique() %>% 
  inner_join(temp, by = c("meetnet", "protocol"))
  
telperiodes <- telperiodes_taak %>%
  bind_rows(telperiodes_wp) %>%
   bind_rows(telperiodes_metadata) %>%
  arrange(meetnet, protocol) %>%
  mutate(protocol = ifelse(meetnet == "Grote weerschijnvlinder", "Vlinders - Gebiedstelling", protocol),
         generatie = ifelse(is.na(generatie), "generatie1", generatie))

```

## Combine metadata

```{r}
metadata <- metadata_file %>%
  select(-start_telperiode, -einde_telperiode) %>%
  left_join(telperiodes, by = c("soortgroep", "meetnet", "protocol", "generatie")) %>%
  left_join(meetnetten_n_locaties, by = c("meetnet")) %>%
  select(actief, everything()) %>%
  mutate(is_sample = ifelse(meetnet == "Gladde slang", TRUE, is_sample),
         n_locaties = ifelse(meetnet == "Gladde slang", 49, n_locaties))
```

## Write 

```{r}
write_vc(metadata, "meetnetkarakteristieken", "../metadata", sorting = c("soortgroep", "meetnet", "protocol", "is_sample"), strict = FALSE)
```
## Figure

```{r}
data_figure <- metadata_file %>%
  mutate(actief = ifelse(meetnet == "Nauwe korfslak", 1, actief)) %>%
  filter(actief == 1) %>%
  distinct(soortgroep, meetnet, type_soort) %>%
  mutate(species_group = ifelse(soortgroep == "amfibieën", "amphibians",
                                ifelse(soortgroep == "andere zoogdieren", "other mammals", 
                                       ifelse(soortgroep == "planten", "plants",
                                              ifelse(soortgroep == "vleermuizen", "bats",
                                                     ifelse(soortgroep == "mollusken", "mollusks",
                                                            ifelse(soortgroep == "libellen", "dragonflies",
                                                                   ifelse(soortgroep == "reptielen", "reptiles",
                                                                          ifelse(str_detect(meetnet, "spin"), "spiders",
                                                                                 ifelse(meetnet %in% c("Roestbruine kniptor", "Vliegend hert", "Vermiljoenkever"), "beetles",
                                                                                        ifelse(soortgroep == "dagvlinders", "butterflies", 
                                                                                               ifelse(meetnet %in% c("Schavertje", "Zadelsprinkhaan"),"grashoppers", "birds")))))))))))) %>%
  filter(meetnet != "Hazelmuis - Nestbuizen") %>%
  filter(!species_group %in% c("bats", "birds"))
                                                                                 
                                                                                            
data_figure_sg <- data_figure %>%
  group_by(species_group, type_soort) %>%
  summarise(n_species = n()) %>%
  ungroup() %>%
  mutate(n_species = ifelse(species_group == "bats", 9, n_species),
         n_species = ifelse(species_group == "birds", max(n_species + 5), n_species),
         label = ifelse(species_group == "birds", "> 150", n_species),
         species_type = ifelse(type_soort == "VPS", "Flemish priority species", "European priority species"))
  
                                
   
 data_figure_sg %>%
   ggplot(aes(x = species_group, y = n_species, fill = species_type, label = label)) +
   geom_col() +
   geom_text( position = position_stack(vjust = 0.5)) +
   coord_flip() +
   labs(x = "Species group", y = "Number of species", fill = "Type",  title = "New monitoring schemes since 2016") +
   theme(legend.position = "bottom")
  
                           
```

